notification added
Eventtia/eventtia-core-docs pull request #27
Opened 2022-09-16 21:45 UTC by PierreQuintero-eventtia

2022-09-16 21:57 UTC, dorozco94 requested changes

2022-09-16 21:57 UTC, dorozco94 commented on source/includes/_notifications.md
> +name       | string  | name for notification
Men todas las descripciones por estándar no deberíamos de manejarlas con mayúscula inicial?

2022-09-16 22:03 UTC, PierreQuintero-eventtia commented on source/includes/_notifications.md
> +name       | string  | name for notification
done

2022-09-19 13:26 UTC, dorozco94 approved these changes

2022-09-26 14:57 UTC, merged