Public endpoints
Eventtia/eventtia-core-docs pull request #29
Opened 2022-10-14 14:47 UTC by PierreQuintero-eventtia

2022-10-14 19:58 UTC, dorozco94 requested changes

2022-10-14 19:58 UTC, dorozco94 commented on source/includes/_public_endpoints.md
> +include   | string | the value settings gives informations for each relationships (settings or attendees)
No te parece mejor men, por convención comenzar las descripciones en mayúscula.?

2022-10-14 19:58 UTC, dorozco94 commented on source/includes/_public_endpoints.md
> +        "price": "34.2",
El price si es un string?

2022-10-14 20:44 UTC, PierreQuintero-eventtia commented on source/includes/_public_endpoints.md
> +        "price": "34.2",
done

2022-10-14 20:44 UTC, PierreQuintero-eventtia commented on source/includes/_public_endpoints.md
> +include   | string | the value settings gives informations for each relationships (settings or attendees)
puede ser

2022-10-18 21:23 UTC, dorozco94 approved these changes
@PierreQuintero-eventtia , quedo super!

2022-10-19 14:18 UTC, merged